mhost/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('mhosts.urls', namespace='mhosts')),
]+ static("/",document_root="./static/")


#for deploying on gunicorn or other
if not settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

mhosts/urls.py
"""Defines url patterns for mhosts."""

from django.conf.urls import url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Home page.
    url(r'^$', views.groups, name='index_groups'),
        # Show all groups.
    url(r'^groups/$', views.groups, name='groups'),
    
    # Detail page for a single group.
    url(r'^groups/(?P<group_id>\d+)/$', views.group, name='group'),

        # Page for adding a new group.
    url(r'^new_group/$', views.new_group, name='new_group'),

        # Page for editing an group.
    url(r'^edit_group/(?P<group_id>\d+)/$', views.edit_group, name='edit_group'),

        # Page for deleting an group.
    url(r'^delete_group/(?P<group_id>\d+)/$', views.delete_group, name='delete_group'),
    
    #Page for adding a new host.
    url(r'^new_host/(?P<group_id>\d+)/$', views.new_host, name='new_host'),

    #Page for searching a new host.
    url(r'^search_host/(?P<group_id>\d+)/$', views.search_host, name='search_host'),
    
    # Page for editing an host.
    url(r'^edit_host/(?P<host_id>\d+)/$', views.edit_host, name='edit_host'),

    # Page for deleting an host.
    url(r'^delete_host/(?P<host_id>\d+)/$', views.delete_host, name='delete_host'),

        #configure IE browser
    url(r'ieconfig/$', views.ieconfig, name='ieconfig'),
]

users/urls.py
"""Defines url patterns for users."""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Login page.
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
        
    # Logout page.
    url(r'^logout/$', views.logout_view, name='logout'),
    
    # Registration page. 
    url(r'^register/$', views.register, name='register'),
]

mhosts/models.py
from django.db import models
from django.contrib.auth.models import User


class Group(models.Model):
    """A host group belongs to a user."""
    text = models.CharField(max_length=100)

    os_type = models.CharField(max_length=20, default="windows")

    # date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        # return self.text + r'(' + self.os_type + r')'
        return self.text


class Host(models.Model):
    """a host that belongs to a group."""
    group = models.ForeignKey(Group)
    # text = models.TextField()
    # date_added = models.DateTimeField(auto_now_add=True)

    host_name = models.CharField(max_length=50)
    host_ip = models.GenericIPAddressField()

    user_name = models.CharField(max_length=50)
    user_pass = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'hosts'

    def __str__(self):
        """Return a string representation of the model."""
        return self.host_name

mhosts/forms.py
from django import forms

from .models import Group, Host

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['text', 'os_type']
        labels = {'text': 'group name'}

class HostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = ['host_name', 'host_ip', 'user_name', 'user_pass']
        labels = {'host_name': 'Host name'}
        # widgets = {'text': forms.Textarea(attrs={'cols': 30})}
        widgets = {'user_pass': forms.PasswordInput(render_value = True)}

mhosts/views.py
import subprocess
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from .models import Group, Host
from .forms import GroupForm, HostForm

from django.db.models import Q

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    """The home page for mhost."""
    """Show all groups, and os_type"""
    groups = Group.objects.filter(owner=request.user).order_by('id')
    context = {'groups': groups}
    return render(request, 'mhosts/groups.html', context)



@login_required
def groups(request):
    """Show all groups, and os_type"""
    groups = Group.objects.filter(owner=request.user).order_by('id')

    ##
    # o = []
    # grp = Group.objects.filter(owner=request.user).order_by('date_added').values()
    # for i in grp:
    #     o.append(i['os_type'])

    ##
    context = {'groups': groups}
    # context = {'groups': groups, 'o': o}
    return render(request, 'mhosts/groups.html', context)


@login_required
def group(request, group_id):
    """Show a single group, and all its hosts."""

    group = Group.objects.get(id=group_id)
    """find group and host query set in database"""
    # 确认请求的主题属于当前用户
    if group.owner != request.user:
        raise Http404
    hosts = group.host_set.order_by('host_ip')
    #.count函数可以查询查询集的数量
    #定义1-300的列表传递给render函数
    # seq = {}
    # seq['c'] = list(range(1,6))

    context = {
        'group': group, 'hosts': hosts, 
    }

    if group.os_type == 'windows':
        return render(request, 'mhosts/win_group.html', context)
    else:
        return render(request, 'mhosts/linux_group.html', context)
    # return render(request, 'mhosts/group.html', context)


def new_group(request):
    """Add a new group."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = GroupForm()
    else:
        # POST data submitted; process data.
        form = GroupForm(request.POST)
        if form.is_valid():
            new_group = form.save(commit=False)
            new_group.owner = request.user
            new_group.save()
            return HttpResponseRedirect(reverse('mhosts:groups'))

    context = {'form': form}
    return render(request, 'mhosts/new_group.html', context)


#新增编辑组
@login_required
def edit_group(request, group_id):
    """Edit an existing group."""
    group = Group.objects.get(id=group_id)
    if group.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current group.
        form = GroupForm(instance=group)
    else:
        # POST data submitted; process data.
        form = GroupForm(instance=group, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mhosts:groups'))

    context = {'group': group, 'form': form}
    return render(request, 'mhosts/edit_group.html', context)


@login_required
def delete_group(request, group_id):
    """delete an existing group."""
    group = Group.objects.get(id=group_id)
    if group.owner != request.user:
        raise Http404

    group.delete()
    return HttpResponseRedirect(reverse('mhosts:groups'))


@login_required
def new_host(request, group_id):
    """Add a new host for a particular group."""
    group = Group.objects.get(id=group_id)
    if group.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = HostForm()

    else:
        # POST data submitted; process data.
        form = HostForm(data=request.POST)

        if form.is_valid():
            new_host = form.save(commit=False)
            new_host.group = group
            new_host.save()

            return HttpResponseRedirect(reverse('mhosts:group',
                                                args=[group_id]))

    context = {'group': group, 'form': form}
    return render(request, 'mhosts/new_host.html', context)

@login_required
def search_host(request, group_id):
    """search a new host in a particular group."""
    group = Group.objects.get(id=group_id)
    if group.owner != request.user:
        raise Http404

    q = request.GET.get('q')

    qs = Host.objects.filter(group_id=group_id)
    hosts = qs.filter(Q(host_ip__icontains=q)|Q(host_name__icontains=q))

    context = {'group': group, 'hosts': hosts}
    if group.os_type == 'windows':
        return render(request, 'mhosts/win_group.html', context)
    else:
        return render(request, 'mhosts/linux_group.html', context)



@login_required
def edit_host(request, host_id):
    """Edit an existing host."""
    host = Host.objects.get(id=host_id)
    group = host.group
    if group.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current host.
        form = HostForm(instance=host)
    else:
        # POST data submitted; process data.
        form = HostForm(instance=host, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mhosts:group',
                                                args=[group.id]))

    context = {'host': host, 'group': group, 'form': form}
    return render(request, 'mhosts/edit_host.html', context)


@login_required
def delete_host(request, host_id):
    """delete an existing host."""
    host = Host.objects.get(id=host_id)
    group = host.group
    if group.owner != request.user:
        raise Http404

    host.delete()
    return HttpResponseRedirect(reverse('mhosts:group',args=[group.id]))

#帮助文件 配置IE浏览器
def ieconfig(request):
    return render(request, 'mhosts/ieconfig.html')

mhosts/templates/mhosts/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>CN04-CORP Server Login</title>

    {% bootstrap_css %} {% bootstrap_javascript %}
    {% load staticfiles %}

    <style>
        body {
            /* background-image: url("{% static "mhosts/images/back.jpg" %}"); */
            background-color:#fdfcf8;
        }
        table{
            width:100%;
            margin:15px 0;
            border:1;
           
        }
        table th{
            background-color:#96C7ED;
            font-size:20px;
            border:1px solid #73b4e7;
            
        }
        table tr td{
            font-size:18px;
            color:black;
            padding:4px;
            border:1px solid #73b4e7;
            border-collapse:collapse;
        }
        .adgr{
            font-size:23px;
        }
        .groupname{
            font-size:30px;
            color:royalblue;
            text-align:center;
        }
        .addnewhost{
            font-size:23px;

            text-align:left;
           
        }
        .addnewhost a:visited{
            color:brown;
        }
        .addnewhost a:hover{
            color:red
        }
       
        
    </style>
</head>

<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top ">
        <div class="container ">
            <div id="navbar " class="navbar-collapse collapse ">
                <h4>
                    <ul class="nav navbar-nav ">
                        <li><a href="{% url 'mhosts:groups' %} ">HOME</a></li>
                    </ul>

                    <!-- <div class="navbar-header">
                      <img class="mb-4" src="{% static 'mhosts/images/logo.png' %}" alt="" width="200" height="30">
                    </div> -->

                    <!-- <div class="navbar-header">
                      <a href="{% url 'mhosts:groups' %}">
                      <img border="0" src="{% static 'mhosts/images/logo.png' %}" alt="" wwidth="190" height="35"></a>
                    </div> -->
                      

                    <ul class="nav navbar-nav navbar-right ">
                        {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %} ">log out</a></li>
                        {% else %}
                        <li><a href="{% url 'users:register' %} ">register</a></li>
                        <li><a href="{% url 'users:login' %} ">log in</a></li>
                        {% endif %}
                    </ul>
                </h4>
        </div>
        <!--/.nav-collapse -->

        </div>
    </nav>

    <div class="container ">

        <div class="page-header ">
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>

    </div>
    <!-- /container -->

</body>

</html>

mhosts/templates/mhosts/base3.html
{% load bootstrap3 %}
<!-- {% bootstrap_css %}  -->
<!-- {% bootstrap_javascript %} -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script> -->

  <title>Veoneer Server Login Platform</title>




  {% load staticfiles %}

  <style>
    body {
      /* background-image: url("{% static "mhosts/images/back.jpg" %}"); */
      background-color: #fdfcf8;
    }

    table {
      width: 100%;
      margin: 15px 0;
      border: 1;

    }

    table th {
      background-color: #96C7ED;
      font-size: 20px;
      border: 1px solid #73b4e7;

    }

    table tr td {
      font-size: 18px;
      color: black;
      padding: 4px;
      border: 1px solid #73b4e7;
      border-collapse: collapse;
    }

    .adgr {
      font-size: 23px;
    }

    .groupname {
      font-size: 30px;
      color: royalblue;
      text-align: center;
    }

    .addnewhost {
      font-size: 23px;

      text-align: left;

    }

    .addnewhost a:visited {
      color: brown;
    }

    .addnewhost a:hover {
      color: red
    }
  </style>
</head>

<body>
  <!--navbar是nav导航标签的一个基类必须添加，navbar-default是对导航条样式的添加-->
  <nav class="navbar navbar-default">
    <!--导航具体内容要放到一个容器里增加一定边距，看起来好看-->
    <div class="container">
      <!--导航条的头部（就是中北大学校徽那个地方）-->
      <div class="navbar-header">
        <img class="mb-4" src="{% static 'mhosts/images/logo.png' %}" alt="" width="200" height="30">
      </div>
      <!--导航链接部分 collapse,nav-collapse是说导航条是一个折叠导航条-->
      <div class="collapse navbar-collapse">
        <!--真正的链接部分是需要添加nav navbar-nav类的-->
        <ul class="nav navbar-nav">
          <li><a href="#">首页</a></li>
          <li><a href="#">保留1</a></li>
          <li><a href="#">保留2</a></li>
          <li><a href="#">保留3</a></li>
        </ul>
        <!-- 靠右的导航条登陆注册  navbar-right-->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a>Hello, {{ user.username }}.</a></li>
          <li><a href="{% url 'users:logout' %} ">log out</a></li>
          {% else %}
          <li><a href="{% url 'users:register' %} ">register</a></li>
          <li><a href="{% url 'users:login' %} ">log in</a></li>
          {% endif %}
        </ul>
      </div>

    </div>

  </nav>

  <a data-toggle="collapse" href="#pp1" class="list-group-item" href="{% url 'mhosts:groups' %} ">Server Groups</a>
  <ul class="collapse list-group" id="pp1" style="margin-bottom=0px">
    <li class="collapse list-group-item"><a href="#">分组1</a></li>
    <li class="collapse list-group-item"><a href="#">分组2</a></li>
    <li class="collapse list-group-item"><a href="#">分组3</a></li>
  </ul>
  <a data-toggle="collapse" href="#pp1" class="list-group-item" href="#pp2">计划任务</a>
  <ul class="collapse list-group" id="pp2" style="margin-bottom=0px">
    <li class="collapse list-group-item"><a href="#">关机</a></li>
    <li class="collapse list-group-item"><a href="#">重启</a></li>
  </ul>


  <div class="container ">

    <div class="page-header ">
        {% block header %}{% endblock %}
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
  
  </div>
  <!-- /container -->
  
</body>



</html>

mhosts/templates/mhosts/edit_group.html
{% extends "mhosts/base.html" %}

{% block content %}
<div class="hostpage">
  <p>
    <h3>
      <a href="{% url 'mhosts:groups' %}">{{ group }}</a>
    </h3>
  </p>
    
  <span>Edit group:</span>
    
  <form action="{% url 'mhosts:edit_group' group.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
</div>
{% endblock content %}

mhosts/templates/mhosts/edit_host.html
{% extends "mhosts/base.html" %}

{% block content %}
<div class="hostpage">
  <p>
    <h3>
      <a href="{% url 'mhosts:group' group.id %}">{{ group }}</a>
    </h3>
  </p>
    
  <span>Edit host:</span>
    
  <form action="{% url 'mhosts:edit_host' host.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>
</div>
{% endblock content %}

mhosts/templates/mhosts/group.html
{% extends 'mhosts/base.html' %} 

{% block header %}
<div class="groupname">{{ group }}</div>
{% endblock header %} 

{% block content %}
<div class="addnewhost">
    <a href="{% url 'mhosts:new_host' group.id %}">add new host</a>

</div>
    


<form role="search" method="get" id="searchform" action="{% url 'mhosts:search_host' group.id %}">
    <input type="search" name="q" placeholder="search hostname or IP" required>
    <button type="submit">search</button>
</form>

<h3 id="{{host.id}}">
    <table >
        
            <tr>
                <!-- <th>ID</th> -->
                <th>Host name</th>
                <th>IP Address</th>
                <th>User Name</th>
                <th colspan="2">actions</th>
                <th colspan="2">console</th>
            </tr>
        
        {% for host in hosts %}
        
            <tr>
                <!-- <td>{{ host.id }}&nbsp;&nbsp;</td> -->
                <td>{{ host.host_name }}&nbsp;&nbsp;</td>
                <td>{{ host.host_ip }}&nbsp;</td>
                <td>{{ host.user_name }}&nbsp;&nbsp;</td>

                <td><a href="{% url 'mhosts:delete_host' host.id %}" onclick="return deleteJob();">
          delete&nbsp;&nbsp;</a></td>
                <td><a href="{% url 'mhosts:edit_host' host.id %}">
          edit&nbsp;&nbsp;</a></td>
                <td><a href="javascript:;" onclick="openRDP{{ host.id }}()">
          RDP&nbsp;&nbsp;</a></td>
                <td><a href="javascript:;" onclick="openSSH{{ host.id }}()">
          SSH</a></td>

            </tr>
       

    <script type="text/javascript">

      var cmd = new ActiveXObject("WScript.Shell");
    
      function openRDP{{ host.id }}() {
        var ip = "{{ host.host_ip }}"
        var User = "{{ host.user_name }}"
        var Password = "{{ host.user_pass }}"
        var cmd_key = "cmdkey /generic:TERMSRV/" + ip + " /user:CN04-CORP\\" + User + " /pass:" + Password
        cmd.run("cmd.exe /c " + cmd_key);
        cmd.run("cmd.exe /c mstsc /f /v:" + ip);
      }
    
      function openSSH{{ host.id }}() {
        cmd.run("cmd.exe /c putty -ssh -l {{ host.user_name }} -pw {{ host.user_pass }} -P 22 {{ host.host_ip }}" );
      }
    
      function deleteJob()
        {
             if(confirm("delete this server?"))
             {
                 return true;
             }else{
                 return false;
           }
        }
    
    </script>

        {% empty %} There is no host in this group yet. 
        
        {% endfor %}
    </table>
</h3>

{% endblock content %}

mhosts/templates/mhosts/ieconfig.html
<p>
1、打开IE浏览器。
</p>
<p>
2、在IE浏览器中找到工具按钮，单击即可。
</p>
<p>
3、选择下面的“INTERNET选项”，并单击。
</p>
<p>
4、然后点击“安全”这个选项，下面会出现相应的菜单。
</p>
<p>
5、在接下来的页面中，选择“可信任站点”。
</p>
<p>
6、接下来选择下方的“自定义级别”这个按钮。
</p>
<p>
7、找到activex控件和插件，启用所有子项就可以啦。
</p>

mhosts/templates/mhosts/linux_group.html
{% extends 'mhosts/base.html' %} {% block header %}

<div class="groupname">{{ group }}</div>

{% endblock header %} {% block content %}
<div class="addnewhost">
    <a href="{% url 'mhosts:new_host' group.id %}">add new host</a>

</div>
    


<form role="search" method="get" id="searchform" action="{% url 'mhosts:search_host' group.id %}">
    <input type="search" name="q" placeholder="search hostname or IP" required>
    <button type="submit">search</button>
</form>

<h3 id="{{host.id}}">
    <table >
        
            <tr>
                <!-- <th>ID</th> -->
                <th>Host name</th>
                <th>IP Address</th>
                <th>User Name</th>
                <th colspan="2">actions</th>
                <th colspan="2">console</th>
            </tr>
        
        {% for host in hosts %}
        
            <tr>
                <!-- <td>{{ host.id }}</td> -->
                <td>{{ host.host_name }}</td>
                <td><a href="javascript:;" onclick="openSSH{{ host.id }}()">
                    {{ host.host_ip }}</a></td>
                <td>{{ host.user_name }}</td>

                <td><a href="{% url 'mhosts:delete_host' host.id %}" onclick="return deleteJob();">
          delete</a></td>
                <td><a href="{% url 'mhosts:edit_host' host.id %}">
          edit</a></td>
                <!-- <td><a href="javascript:;" onclick="openRDP{{ host.id }}()">
          RDP</a></td> -->
                <td><a href="javascript:;" onclick="openSSH{{ host.id }}()">
          SSH</a></td>

            </tr>
       

    <script type="text/javascript">

      var cmd = new ActiveXObject("WScript.Shell");
    
      function openRDP{{ host.id }}() {
        var ip = "{{ host.host_ip }}"
        var User = "{{ host.user_name }}"
        var Password = "{{ host.user_pass }}"
        var cmd_key = "cmdkey /generic:TERMSRV/" + ip + " /user:CN04-CORP\\" + User + " /pass:" + Password
        cmd.run("cmd.exe /c " + cmd_key);
        cmd.run("cmd.exe /c mstsc /f /v:" + ip);
      }
    
      function openSSH{{ host.id }}() {
        cmd.run("cmd.exe /c putty -ssh -l {{ host.user_name }} -pw {{ host.user_pass }} -P 22 {{ host.host_ip }}" );
      }
    
      function deleteJob()
        {
             if(confirm("delete this server?"))
             {
                 return true;
             }else{
                 return false;
           }
        }
    
    </script>

        {% empty %} There is no host in this group yet. 
        
        {% endfor %}
    </table>
</h3>

{% endblock content %}

mhosts/templates/mhosts/win_group copy.html
{% extends 'mhosts/base.html' %}

{% block header %}
<h2>{{ group }}</h2>
{% endblock header %}

{% block content %}
<p>
  <a href="{% url 'mhosts:new_host' group.id %}">add new host</a>
</p>

<form role="search" method="get" id="searchform" action="{% url 'mhosts:search_host' group.id %}">
	<input type="search" name="q" placeholder="search hostname or IP" required>
	<button type="submit">search</button>
</form>

{% for host in hosts %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      {{ host.host_name }}
      <small>
        <a href="{% url 'mhosts:delete_host' host.id %}" onclick="return deleteJob();">
          delete</a>
        <a href="{% url 'mhosts:edit_host' host.id %}">
          edit</a>
        <a href="javascript:;" onclick="openCmd{{ host.id }}()">
          connect_with_RDP</a>

      </small>
    </h3>
  </div>
  <div id="{{host.id}}" class="panel-body">
    {{ host.id|linebreaks }}
    {{ host.host_ip|linebreaks }}
    {{ host.user_name|linebreaks }}
    <!-- {{ host.text|linebreaks }} -->

  </div>
</div> <!-- panel -->
<script type="text/javascript">

  var cmd = new ActiveXObject("WScript.Shell");

  function openCmd{{ host.id }}() {
    var ip = "{{ host.host_ip }}"
    var User = "{{ host.user_name }}"
    var Password = "{{ host.user_pass }}"
    var cmd_key = "cmdkey /generic:TERMSRV/" + ip + " /user:CN04-CORP\\" + User + " /pass:" + Password
    cmd.run("cmd.exe /c " + cmd_key);
    cmd.run("cmd.exe /c mstsc /f /v:" + ip);
  }

  function deleteJob()
		{
		     if(confirm("delete this server?"))
		     {
		         return true;
		     }else{
		         return false;
			 }
		}

</script>
{% empty %}
There is no host in this group yet.
{% endfor %}

{% endblock content %}

mhosts/templates/mhosts/win_group.html
{% extends 'mhosts/base.html' %} {% block header %}

<div class="groupname">{{ group }}</div>

{% endblock header %} {% block content %}
<div class="addnewhost">
    <a href="{% url 'mhosts:new_host' group.id %}">add new host</a>

</div>
    


<form role="search" method="get" id="searchform" action="{% url 'mhosts:search_host' group.id %}">
    <input type="search" name="q" placeholder="search hostname or IP" required>
    <button type="submit">search</button>
</form>

<h3 id="{{host.id}}">
    <table >
        
            <tr>
                <!-- <th>ID</th> -->
                <th>Host name</th>
                <th>IP Address</th>
                <th>User Name</th>
                <th colspan="2">actions</th>
                <th colspan="2">console</th>
            </tr>
        
        {% for host in hosts %}
        
            <tr>
                <!-- <td>{{ host.id }}&nbsp;&nbsp;</td> -->
                <td>{{ host.host_name }}</td>
                <td><a href="javascript:;" onclick="openRDP{{ host.id }}()">
                    {{ host.host_ip }}</a></td>
                <td>{{ host.user_name }}</td>

                <td><a href="{% url 'mhosts:delete_host' host.id %}" onclick="return deleteJob();">
          delete</a></td>
                <td><a href="{% url 'mhosts:edit_host' host.id %}">
          edit</a></td>
                <td><a href="javascript:;" onclick="openRDP{{ host.id }}()">
          RDP</a></td>
                <!-- <td><a href="javascript:;" onclick="openSSH{{ host.id }}()">
          SSH</a></td> -->

            </tr>
       

    <script type="text/javascript">

      var cmd = new ActiveXObject("WScript.Shell");
    
      function openRDP{{ host.id }}() {
        var ip = "{{ host.host_ip }}"
        var User = "{{ host.user_name }}"
        var Password = "{{ host.user_pass }}"
        var cmd_key = "cmdkey /generic:TERMSRV/" + ip + " /user:CN04-CORP\\" + User + " /pass:" + Password
        cmd.run("cmd.exe /c " + cmd_key);
        cmd.run("cmd.exe /c mstsc /f /v:" + ip);
      }
    
      function openSSH{{ host.id }}() {
        cmd.run("cmd.exe /c putty -ssh -l {{ host.user_name }} -pw {{ host.user_pass }} -P 22 {{ host.host_ip }}" );
      }
    
      function deleteJob()
        {
             if(confirm("delete this server?"))
             {
                 return true;
             }else{
                 return false;
           }
        }
    
    </script>

        {% empty %} There is no host in this group yet. 
        
        {% endfor %}
    </table>
</h3>

{% endblock content %}